### ISSUE TITLE
GridSearch and RandomizedSearch

### ISSUE THREAD

**Issue by manh4wk** [usaa/vogel#1]
The GridSearch and RandomizedSearch methods for cross-validation don't work with the statsmodels models, such as GLMs.

**Comment by TweeDice** [comment]
Thanks for finding that. I am currently working on the fix.

**Comment by TweeDice** [comment]
I don't see any support for hyp param tuning on statsmodels. The only examples I can find are people creating for loops over combinations of params. At that point, I think it's better to just run multiple param sets in vogel
